### PR TITLE
DA features 1666 and 1669

### PR DESCRIPTION
**Pull request by joostdekeijzer**
The css edits are not minified. Is it possible to add the not-minified css to the repository? It will make it easier to change. Thanks!

### CODE REVIEW

**Comment by smicroz** [comment]
I still have vacation days, but I'll try to add css stylus to improve support.

**Comment by joostdekeijzer** [comment]
Updated this PR to the new version.

Spanish translation is missing some entries, eg. `lang/es/admin/custom_httpd_domain.html`

**Comment by joostdekeijzer** [comment]
For your information, links to the DA features:
http://www.directadmin.com/features.php?id=1666
http://www.directadmin.com/features.php?id=1669

And some screendumps of the endresult:

custom template notifications
Inserts the "custom template" notifications (in blue)

template diff
Template diff (after clicking the notification)

**Comment by smicroz** [comment]
I added spanish language from http://forum.directadmin.com/showthread.php?t=41920&p=263142#post263142

There some conflicts to merge this changes

**Comment by joostdekeijzer** [comment]
Merged master code into PR and resolved any conflicts.

**Comment by smicroz** [comment]
Perfect, now is merged.

**Pull request merged**
